vich_uploader:
    db_driver: orm
    mappings:
        stage_gpx:
            uri_prefix: /uploads/gpx
            upload_destination: '%kernel.project_dir%/public/uploads/gpx'
            # allow_overwrite: false
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
