vich_uploader:
    db_driver: orm
    mappings:
        stage_gpx:
            uri_prefix: /uploads/gpx
            upload_destination: '%kernel.project_dir%/public/uploads/gpx'
            # allow_overwrite: false
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

        images:
            uri_prefix: /images
            upload_destination: '%kernel.project_dir%/public/images'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
            delete_on_remove: true
            delete_on_update: true
